// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package com.protos;

public final class MsgDataProtos {
  private MsgDataProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MsgDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:tutorial.MsgData)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string handle = 1;</code>
     * @return Whether the handle field is set.
     */
    boolean hasHandle();
    /**
     * <code>optional string handle = 1;</code>
     * @return The handle.
     */
    java.lang.String getHandle();
    /**
     * <code>optional string handle = 1;</code>
     * @return The bytes for handle.
     */
    com.google.protobuf.ByteString
        getHandleBytes();

    /**
     * <code>optional int32 msgId = 2;</code>
     * @return Whether the msgId field is set.
     */
    boolean hasMsgId();
    /**
     * <code>optional int32 msgId = 2;</code>
     * @return The msgId.
     */
    int getMsgId();

    /**
     * <code>optional string sender = 3;</code>
     * @return Whether the sender field is set.
     */
    boolean hasSender();
    /**
     * <code>optional string sender = 3;</code>
     * @return The sender.
     */
    java.lang.String getSender();
    /**
     * <code>optional string sender = 3;</code>
     * @return The bytes for sender.
     */
    com.google.protobuf.ByteString
        getSenderBytes();

    /**
     * <code>optional string recipient = 4;</code>
     * @return Whether the recipient field is set.
     */
    boolean hasRecipient();
    /**
     * <code>optional string recipient = 4;</code>
     * @return The recipient.
     */
    java.lang.String getRecipient();
    /**
     * <code>optional string recipient = 4;</code>
     * @return The bytes for recipient.
     */
    com.google.protobuf.ByteString
        getRecipientBytes();

    /**
     * <code>optional string body = 5;</code>
     * @return Whether the body field is set.
     */
    boolean hasBody();
    /**
     * <code>optional string body = 5;</code>
     * @return The body.
     */
    java.lang.String getBody();
    /**
     * <code>optional string body = 5;</code>
     * @return The bytes for body.
     */
    com.google.protobuf.ByteString
        getBodyBytes();

    /**
     * <code>optional .tutorial.MsgData.Type type = 6;</code>
     * @return Whether the type field is set.
     */
    boolean hasType();
    /**
     * <code>optional .tutorial.MsgData.Type type = 6;</code>
     * @return The type.
     */
        com.protos.MsgDataProtos.MsgData.Type getType();

    /**
     * <code>repeated string agents = 7;</code>
     * @return A list containing the agents.
     */
    java.util.List<java.lang.String>
        getAgentsList();
    /**
     * <code>repeated string agents = 7;</code>
     * @return The count of agents.
     */
    int getAgentsCount();
    /**
     * <code>repeated string agents = 7;</code>
     * @param index The index of the element to return.
     * @return The agents at the given index.
     */
    java.lang.String getAgents(int index);
    /**
     * <code>repeated string agents = 7;</code>
     * @param index The index of the value to return.
     * @return The bytes of the agents at the given index.
     */
    com.google.protobuf.ByteString
        getAgentsBytes(int index);
  }
  /**
   * Protobuf type {@code tutorial.MsgData}
   */
  public  static final class MsgData extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:tutorial.MsgData)
      MsgDataOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MsgData.newBuilder() to construct.
    private MsgData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MsgData() {
      handle_ = "";
      sender_ = "";
      recipient_ = "";
      body_ = "";
      type_ = 0;
      agents_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new MsgData();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MsgData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              handle_ = bs;
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              msgId_ = input.readInt32();
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              sender_ = bs;
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              recipient_ = bs;
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000010;
              body_ = bs;
              break;
            }
            case 48: {
              int rawValue = input.readEnum();
                @SuppressWarnings("deprecation")
                        com.protos.MsgDataProtos.MsgData.Type value = com.protos.MsgDataProtos.MsgData.Type.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(6, rawValue);
              } else {
                bitField0_ |= 0x00000020;
                type_ = rawValue;
              }
              break;
            }
            case 58: {
              com.google.protobuf.ByteString bs = input.readBytes();
              if (!((mutable_bitField0_ & 0x00000040) != 0)) {
                agents_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000040;
              }
              agents_.add(bs);
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000040) != 0)) {
          agents_ = agents_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.protos.MsgDataProtos.internal_static_tutorial_MsgData_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.protos.MsgDataProtos.internal_static_tutorial_MsgData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(com.protos.MsgDataProtos.MsgData.class, com.protos.MsgDataProtos.MsgData.Builder.class);
    }

    /**
     * Protobuf enum {@code tutorial.MsgData.Type}
     */
    public enum Type
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>USER = 0;</code>
       */
      USER(0),
      /**
       * <code>ADD = 1;</code>
       */
      ADD(1),
      /**
       * <code>REMOVE = 2;</code>
       */
      REMOVE(2),
      /**
       * <code>HANDLE = 3;</code>
       */
      HANDLE(3),
      /**
       * <code>LIST = 4;</code>
       */
      LIST(4),
      /**
       * <code>RETURN = 5;</code>
       */
      RETURN(5),
      ;

      /**
       * <code>USER = 0;</code>
       */
      public static final int USER_VALUE = 0;
      /**
       * <code>ADD = 1;</code>
       */
      public static final int ADD_VALUE = 1;
      /**
       * <code>REMOVE = 2;</code>
       */
      public static final int REMOVE_VALUE = 2;
      /**
       * <code>HANDLE = 3;</code>
       */
      public static final int HANDLE_VALUE = 3;
      /**
       * <code>LIST = 4;</code>
       */
      public static final int LIST_VALUE = 4;
      /**
       * <code>RETURN = 5;</code>
       */
      public static final int RETURN_VALUE = 5;


      public final int getNumber() {
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static Type valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static Type forNumber(int value) {
        switch (value) {
          case 0: return USER;
          case 1: return ADD;
          case 2: return REMOVE;
          case 3: return HANDLE;
          case 4: return LIST;
          case 5: return RETURN;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Type>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Type> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Type>() {
              public Type findValueByNumber(int number) {
                return Type.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return  com.protos.MsgDataProtos.MsgData.getDescriptor().getEnumTypes().get(0);
      }

      private static final Type[] VALUES = values();

      public static Type valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private Type(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:tutorial.MsgData.Type)
    }

    private int bitField0_;
    public static final int HANDLE_FIELD_NUMBER = 1;
    private volatile java.lang.Object handle_;
    /**
     * <code>optional string handle = 1;</code>
     * @return Whether the handle field is set.
     */
    public boolean hasHandle() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional string handle = 1;</code>
     * @return The handle.
     */
    public java.lang.String getHandle() {
      java.lang.Object ref = handle_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          handle_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string handle = 1;</code>
     * @return The bytes for handle.
     */
    public com.google.protobuf.ByteString
        getHandleBytes() {
      java.lang.Object ref = handle_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        handle_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MSGID_FIELD_NUMBER = 2;
    private int msgId_;
    /**
     * <code>optional int32 msgId = 2;</code>
     * @return Whether the msgId field is set.
     */
    public boolean hasMsgId() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional int32 msgId = 2;</code>
     * @return The msgId.
     */
    public int getMsgId() {
      return msgId_;
    }

    public static final int SENDER_FIELD_NUMBER = 3;
    private volatile java.lang.Object sender_;
    /**
     * <code>optional string sender = 3;</code>
     * @return Whether the sender field is set.
     */
    public boolean hasSender() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional string sender = 3;</code>
     * @return The sender.
     */
    public java.lang.String getSender() {
      java.lang.Object ref = sender_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          sender_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string sender = 3;</code>
     * @return The bytes for sender.
     */
    public com.google.protobuf.ByteString
        getSenderBytes() {
      java.lang.Object ref = sender_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sender_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RECIPIENT_FIELD_NUMBER = 4;
    private volatile java.lang.Object recipient_;
    /**
     * <code>optional string recipient = 4;</code>
     * @return Whether the recipient field is set.
     */
    public boolean hasRecipient() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional string recipient = 4;</code>
     * @return The recipient.
     */
    public java.lang.String getRecipient() {
      java.lang.Object ref = recipient_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          recipient_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string recipient = 4;</code>
     * @return The bytes for recipient.
     */
    public com.google.protobuf.ByteString
        getRecipientBytes() {
      java.lang.Object ref = recipient_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        recipient_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BODY_FIELD_NUMBER = 5;
    private volatile java.lang.Object body_;
    /**
     * <code>optional string body = 5;</code>
     * @return Whether the body field is set.
     */
    public boolean hasBody() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>optional string body = 5;</code>
     * @return The body.
     */
    public java.lang.String getBody() {
      java.lang.Object ref = body_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          body_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string body = 5;</code>
     * @return The bytes for body.
     */
    public com.google.protobuf.ByteString
        getBodyBytes() {
      java.lang.Object ref = body_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        body_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TYPE_FIELD_NUMBER = 6;
    private int type_;
    /**
     * <code>optional .tutorial.MsgData.Type type = 6;</code>
     * @return Whether the type field is set.
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <code>optional .tutorial.MsgData.Type type = 6;</code>
     * @return The type.
     */
    public com.protos.MsgDataProtos.MsgData.Type getType() {
      @SuppressWarnings("deprecation")
            com.protos.MsgDataProtos.MsgData.Type result = com.protos.MsgDataProtos.MsgData.Type.valueOf(type_);
      return result == null ? com.protos.MsgDataProtos.MsgData.Type.USER : result;
    }

    public static final int AGENTS_FIELD_NUMBER = 7;
    private com.google.protobuf.LazyStringList agents_;
    /**
     * <code>repeated string agents = 7;</code>
     * @return A list containing the agents.
     */
    public com.google.protobuf.ProtocolStringList
        getAgentsList() {
      return agents_;
    }
    /**
     * <code>repeated string agents = 7;</code>
     * @return The count of agents.
     */
    public int getAgentsCount() {
      return agents_.size();
    }
    /**
     * <code>repeated string agents = 7;</code>
     * @param index The index of the element to return.
     * @return The agents at the given index.
     */
    public java.lang.String getAgents(int index) {
      return agents_.get(index);
    }
    /**
     * <code>repeated string agents = 7;</code>
     * @param index The index of the value to return.
     * @return The bytes of the agents at the given index.
     */
    public com.google.protobuf.ByteString
        getAgentsBytes(int index) {
      return agents_.getByteString(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, handle_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeInt32(2, msgId_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, sender_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, recipient_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, body_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        output.writeEnum(6, type_);
      }
      for (int i = 0; i < agents_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, agents_.getRaw(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, handle_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, msgId_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, sender_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, recipient_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, body_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(6, type_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < agents_.size(); i++) {
          dataSize += computeStringSizeNoTag(agents_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getAgentsList().size();
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.protos.MsgDataProtos.MsgData)) {
        return super.equals(obj);
      }
            com.protos.MsgDataProtos.MsgData other = (com.protos.MsgDataProtos.MsgData) obj;

      if (hasHandle() != other.hasHandle()) return false;
      if (hasHandle()) {
        if (!getHandle()
            .equals(other.getHandle())) return false;
      }
      if (hasMsgId() != other.hasMsgId()) return false;
      if (hasMsgId()) {
        if (getMsgId()
            != other.getMsgId()) return false;
      }
      if (hasSender() != other.hasSender()) return false;
      if (hasSender()) {
        if (!getSender()
            .equals(other.getSender())) return false;
      }
      if (hasRecipient() != other.hasRecipient()) return false;
      if (hasRecipient()) {
        if (!getRecipient()
            .equals(other.getRecipient())) return false;
      }
      if (hasBody() != other.hasBody()) return false;
      if (hasBody()) {
        if (!getBody()
            .equals(other.getBody())) return false;
      }
      if (hasType() != other.hasType()) return false;
      if (hasType()) {
        if (type_ != other.type_) return false;
      }
      if (!getAgentsList()
          .equals(other.getAgentsList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasHandle()) {
        hash = (37 * hash) + HANDLE_FIELD_NUMBER;
        hash = (53 * hash) + getHandle().hashCode();
      }
      if (hasMsgId()) {
        hash = (37 * hash) + MSGID_FIELD_NUMBER;
        hash = (53 * hash) + getMsgId();
      }
      if (hasSender()) {
        hash = (37 * hash) + SENDER_FIELD_NUMBER;
        hash = (53 * hash) + getSender().hashCode();
      }
      if (hasRecipient()) {
        hash = (37 * hash) + RECIPIENT_FIELD_NUMBER;
        hash = (53 * hash) + getRecipient().hashCode();
      }
      if (hasBody()) {
        hash = (37 * hash) + BODY_FIELD_NUMBER;
        hash = (53 * hash) + getBody().hashCode();
      }
      if (hasType()) {
        hash = (37 * hash) + TYPE_FIELD_NUMBER;
        hash = (53 * hash) + type_;
      }
      if (getAgentsCount() > 0) {
        hash = (37 * hash) + AGENTS_FIELD_NUMBER;
        hash = (53 * hash) + getAgentsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.protos.MsgDataProtos.MsgData parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.protos.MsgDataProtos.MsgData parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.protos.MsgDataProtos.MsgData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.protos.MsgDataProtos.MsgData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.protos.MsgDataProtos.MsgData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.protos.MsgDataProtos.MsgData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.protos.MsgDataProtos.MsgData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.protos.MsgDataProtos.MsgData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.protos.MsgDataProtos.MsgData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.protos.MsgDataProtos.MsgData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.protos.MsgDataProtos.MsgData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.protos.MsgDataProtos.MsgData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.protos.MsgDataProtos.MsgData prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code tutorial.MsgData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:tutorial.MsgData)
        com.protos.MsgDataProtos.MsgDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return  com.protos.MsgDataProtos.internal_static_tutorial_MsgData_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return  com.protos.MsgDataProtos.internal_static_tutorial_MsgData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(com.protos.MsgDataProtos.MsgData.class, com.protos.MsgDataProtos.MsgData.Builder.class);
      }

      // Construct using com.example.tutorial.MsgDataProtos.MsgData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        handle_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        msgId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        sender_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        recipient_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        body_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        type_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        agents_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000040);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return  com.protos.MsgDataProtos.internal_static_tutorial_MsgData_descriptor;
      }

      @java.lang.Override
      public com.protos.MsgDataProtos.MsgData getDefaultInstanceForType() {
        return  com.protos.MsgDataProtos.MsgData.getDefaultInstance();
      }

      @java.lang.Override
      public com.protos.MsgDataProtos.MsgData build() {
                com.protos.MsgDataProtos.MsgData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.protos.MsgDataProtos.MsgData buildPartial() {
                com.protos.MsgDataProtos.MsgData result = new com.protos.MsgDataProtos.MsgData(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.handle_ = handle_;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.msgId_ = msgId_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          to_bitField0_ |= 0x00000004;
        }
        result.sender_ = sender_;
        if (((from_bitField0_ & 0x00000008) != 0)) {
          to_bitField0_ |= 0x00000008;
        }
        result.recipient_ = recipient_;
        if (((from_bitField0_ & 0x00000010) != 0)) {
          to_bitField0_ |= 0x00000010;
        }
        result.body_ = body_;
        if (((from_bitField0_ & 0x00000020) != 0)) {
          to_bitField0_ |= 0x00000020;
        }
        result.type_ = type_;
        if (((bitField0_ & 0x00000040) != 0)) {
          agents_ = agents_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000040);
        }
        result.agents_ = agents_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.protos.MsgDataProtos.MsgData) {
          return mergeFrom((com.protos.MsgDataProtos.MsgData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.protos.MsgDataProtos.MsgData other) {
        if (other == com.protos.MsgDataProtos.MsgData.getDefaultInstance()) return this;
        if (other.hasHandle()) {
          bitField0_ |= 0x00000001;
          handle_ = other.handle_;
          onChanged();
        }
        if (other.hasMsgId()) {
          setMsgId(other.getMsgId());
        }
        if (other.hasSender()) {
          bitField0_ |= 0x00000004;
          sender_ = other.sender_;
          onChanged();
        }
        if (other.hasRecipient()) {
          bitField0_ |= 0x00000008;
          recipient_ = other.recipient_;
          onChanged();
        }
        if (other.hasBody()) {
          bitField0_ |= 0x00000010;
          body_ = other.body_;
          onChanged();
        }
        if (other.hasType()) {
          setType(other.getType());
        }
        if (!other.agents_.isEmpty()) {
          if (agents_.isEmpty()) {
            agents_ = other.agents_;
            bitField0_ = (bitField0_ & ~0x00000040);
          } else {
            ensureAgentsIsMutable();
            agents_.addAll(other.agents_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
                com.protos.MsgDataProtos.MsgData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.protos.MsgDataProtos.MsgData) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object handle_ = "";
      /**
       * <code>optional string handle = 1;</code>
       * @return Whether the handle field is set.
       */
      public boolean hasHandle() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional string handle = 1;</code>
       * @return The handle.
       */
      public java.lang.String getHandle() {
        java.lang.Object ref = handle_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            handle_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string handle = 1;</code>
       * @return The bytes for handle.
       */
      public com.google.protobuf.ByteString
          getHandleBytes() {
        java.lang.Object ref = handle_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          handle_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string handle = 1;</code>
       * @param value The handle to set.
       * @return This builder for chaining.
       */
      public Builder setHandle(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        handle_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string handle = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearHandle() {
        bitField0_ = (bitField0_ & ~0x00000001);
        handle_ = getDefaultInstance().getHandle();
        onChanged();
        return this;
      }
      /**
       * <code>optional string handle = 1;</code>
       * @param value The bytes for handle to set.
       * @return This builder for chaining.
       */
      public Builder setHandleBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        handle_ = value;
        onChanged();
        return this;
      }

      private int msgId_ ;
      /**
       * <code>optional int32 msgId = 2;</code>
       * @return Whether the msgId field is set.
       */
      public boolean hasMsgId() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional int32 msgId = 2;</code>
       * @return The msgId.
       */
      public int getMsgId() {
        return msgId_;
      }
      /**
       * <code>optional int32 msgId = 2;</code>
       * @param value The msgId to set.
       * @return This builder for chaining.
       */
      public Builder setMsgId(int value) {
        bitField0_ |= 0x00000002;
        msgId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 msgId = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearMsgId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        msgId_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object sender_ = "";
      /**
       * <code>optional string sender = 3;</code>
       * @return Whether the sender field is set.
       */
      public boolean hasSender() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>optional string sender = 3;</code>
       * @return The sender.
       */
      public java.lang.String getSender() {
        java.lang.Object ref = sender_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            sender_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string sender = 3;</code>
       * @return The bytes for sender.
       */
      public com.google.protobuf.ByteString
          getSenderBytes() {
        java.lang.Object ref = sender_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sender_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string sender = 3;</code>
       * @param value The sender to set.
       * @return This builder for chaining.
       */
      public Builder setSender(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        sender_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string sender = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearSender() {
        bitField0_ = (bitField0_ & ~0x00000004);
        sender_ = getDefaultInstance().getSender();
        onChanged();
        return this;
      }
      /**
       * <code>optional string sender = 3;</code>
       * @param value The bytes for sender to set.
       * @return This builder for chaining.
       */
      public Builder setSenderBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        sender_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object recipient_ = "";
      /**
       * <code>optional string recipient = 4;</code>
       * @return Whether the recipient field is set.
       */
      public boolean hasRecipient() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>optional string recipient = 4;</code>
       * @return The recipient.
       */
      public java.lang.String getRecipient() {
        java.lang.Object ref = recipient_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            recipient_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string recipient = 4;</code>
       * @return The bytes for recipient.
       */
      public com.google.protobuf.ByteString
          getRecipientBytes() {
        java.lang.Object ref = recipient_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          recipient_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string recipient = 4;</code>
       * @param value The recipient to set.
       * @return This builder for chaining.
       */
      public Builder setRecipient(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        recipient_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string recipient = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearRecipient() {
        bitField0_ = (bitField0_ & ~0x00000008);
        recipient_ = getDefaultInstance().getRecipient();
        onChanged();
        return this;
      }
      /**
       * <code>optional string recipient = 4;</code>
       * @param value The bytes for recipient to set.
       * @return This builder for chaining.
       */
      public Builder setRecipientBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        recipient_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object body_ = "";
      /**
       * <code>optional string body = 5;</code>
       * @return Whether the body field is set.
       */
      public boolean hasBody() {
        return ((bitField0_ & 0x00000010) != 0);
      }
      /**
       * <code>optional string body = 5;</code>
       * @return The body.
       */
      public java.lang.String getBody() {
        java.lang.Object ref = body_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            body_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string body = 5;</code>
       * @return The bytes for body.
       */
      public com.google.protobuf.ByteString
          getBodyBytes() {
        java.lang.Object ref = body_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          body_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string body = 5;</code>
       * @param value The body to set.
       * @return This builder for chaining.
       */
      public Builder setBody(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        body_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string body = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearBody() {
        bitField0_ = (bitField0_ & ~0x00000010);
        body_ = getDefaultInstance().getBody();
        onChanged();
        return this;
      }
      /**
       * <code>optional string body = 5;</code>
       * @param value The bytes for body to set.
       * @return This builder for chaining.
       */
      public Builder setBodyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        body_ = value;
        onChanged();
        return this;
      }

      private int type_ = 0;
      /**
       * <code>optional .tutorial.MsgData.Type type = 6;</code>
       * @return Whether the type field is set.
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000020) != 0);
      }
      /**
       * <code>optional .tutorial.MsgData.Type type = 6;</code>
       * @return The type.
       */
      public com.protos.MsgDataProtos.MsgData.Type getType() {
        @SuppressWarnings("deprecation")
                com.protos.MsgDataProtos.MsgData.Type result = com.protos.MsgDataProtos.MsgData.Type.valueOf(type_);
        return result == null ? com.protos.MsgDataProtos.MsgData.Type.USER : result;
      }
      /**
       * <code>optional .tutorial.MsgData.Type type = 6;</code>
       * @param value The type to set.
       * @return This builder for chaining.
       */
      public Builder setType(com.protos.MsgDataProtos.MsgData.Type value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000020;
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional .tutorial.MsgData.Type type = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000020);
        type_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList agents_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureAgentsIsMutable() {
        if (!((bitField0_ & 0x00000040) != 0)) {
          agents_ = new com.google.protobuf.LazyStringArrayList(agents_);
          bitField0_ |= 0x00000040;
         }
      }
      /**
       * <code>repeated string agents = 7;</code>
       * @return A list containing the agents.
       */
      public com.google.protobuf.ProtocolStringList
          getAgentsList() {
        return agents_.getUnmodifiableView();
      }
      /**
       * <code>repeated string agents = 7;</code>
       * @return The count of agents.
       */
      public int getAgentsCount() {
        return agents_.size();
      }
      /**
       * <code>repeated string agents = 7;</code>
       * @param index The index of the element to return.
       * @return The agents at the given index.
       */
      public java.lang.String getAgents(int index) {
        return agents_.get(index);
      }
      /**
       * <code>repeated string agents = 7;</code>
       * @param index The index of the value to return.
       * @return The bytes of the agents at the given index.
       */
      public com.google.protobuf.ByteString
          getAgentsBytes(int index) {
        return agents_.getByteString(index);
      }
      /**
       * <code>repeated string agents = 7;</code>
       * @param index The index to set the value at.
       * @param value The agents to set.
       * @return This builder for chaining.
       */
      public Builder setAgents(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureAgentsIsMutable();
        agents_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string agents = 7;</code>
       * @param value The agents to add.
       * @return This builder for chaining.
       */
      public Builder addAgents(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureAgentsIsMutable();
        agents_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string agents = 7;</code>
       * @param values The agents to add.
       * @return This builder for chaining.
       */
      public Builder addAllAgents(
          java.lang.Iterable<java.lang.String> values) {
        ensureAgentsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, agents_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string agents = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearAgents() {
        agents_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000040);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string agents = 7;</code>
       * @param value The bytes of the agents to add.
       * @return This builder for chaining.
       */
      public Builder addAgentsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureAgentsIsMutable();
        agents_.add(value);
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:tutorial.MsgData)
    }

    // @@protoc_insertion_point(class_scope:tutorial.MsgData)
    private static final com.protos.MsgDataProtos.MsgData DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.protos.MsgDataProtos.MsgData();
    }

    public static com.protos.MsgDataProtos.MsgData getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<MsgData>
        PARSER = new com.google.protobuf.AbstractParser<MsgData>() {
      @java.lang.Override
      public MsgData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MsgData(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MsgData> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MsgData> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.protos.MsgDataProtos.MsgData getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tutorial_MsgData_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tutorial_MsgData_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rmessage.proto\022\010tutorial\"\330\001\n\007MsgData\022\016\n" +
      "\006handle\030\001 \001(\t\022\r\n\005msgId\030\002 \001(\005\022\016\n\006sender\030\003" +
      " \001(\t\022\021\n\trecipient\030\004 \001(\t\022\014\n\004body\030\005 \001(\t\022$\n" +
      "\004type\030\006 \001(\0162\026.tutorial.MsgData.Type\022\016\n\006a" +
      "gents\030\007 \003(\t\"G\n\004Type\022\010\n\004USER\020\000\022\007\n\003ADD\020\001\022\n" +
      "\n\006REMOVE\020\002\022\n\n\006HANDLE\020\003\022\010\n\004LIST\020\004\022\n\n\006RETU" +
      "RN\020\005B%\n\024com.example.tutorialB\rMsgDataPro" +
      "tos"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_tutorial_MsgData_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_tutorial_MsgData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tutorial_MsgData_descriptor,
        new java.lang.String[] { "Handle", "MsgId", "Sender", "Recipient", "Body", "Type", "Agents", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
